<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Settings">
        <text>nuToolbox</text>

        <Action name="showToolbox">
        <icon></icon>
        <text>Show/Hide the Toolbox</text>
        <whatsThis>Show/Hide the Toolbox</whatsThis>
        <toolTip>Show/Hide the Toolbox</toolTip>
        <iconText>nT</iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>t</shortcut>
        <isCheckable>true</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>