<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Settings">
        <text>nuTools</text>

        <Action name="showToolbox">
        <icon></icon>
        <text>Show/Hide the Toolbox</text>
        <whatsThis>Show/Hide the Toolbox</whatsThis>
        <toolTip>Show/Hide the Toolbox</toolTip>
        <iconText>nT</iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>shift+t</shortcut>
        <isCheckable>true</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="showToolOptions">
        <icon></icon>
        <text>Show/Hide the Tool Options</text>
        <whatsThis>Show/Hide the Tool Options</whatsThis>
        <toolTip>Show/Hide the Tool Options</toolTip>
        <iconText>nT</iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>n</shortcut>
        <isCheckable>true</isCheckable>
        <statusTip></statusTip>
        </Action>

    </Actions>
</ActionCollection>
